GET http://localhost:3002/api/persons

###


DELETE http://localhost:3002/api/persons/67d84850f332fc743e4877a6



###


POST http://localhost:3002/api/persons
Content-Type: application/json

{
 "name": "aa",
    "number": "12-164525"
}